version: '3.9'

services:
  traefik:
    image: traefik:latest
    container_name: "traefik"
    restart: unless-stopped
    command:
      # Traefik will listen on port 8080 by default for API request.
      - "--api.insecure=true"
      # Enabling Docker provider
      - "--providers.docker=true"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
      # Traefik will listen to incoming request on the port 80 (HTTP)
      - "--entrypoints.web.address=:80"
      # Traefik will listen to incoming request on the port 443 (https)
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
      - "--entryPoints.websecure.http.tls.certresolver=step"
      - "--certificatesresolvers.step.acme.caserver=https://step:9000/acme/acme/directory"
      - "--certificatesresolvers.step.acme.tlschallenge=true"
      - "--certificatesresolvers.step.acme.email=root@localhost"
      - "--certificatesresolvers.step.acme.keytype=RSA4096"
      - "--certificatesresolvers.step.acme.storage=acme.json"
    environment:
      - TZ=UTC
      - LEGO_CA_CERTIFICATES=/step/certs/root_ca.crt
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Create a stepca dir within the folder where the docker-compose file is
      - ./acme.json:/acme.json
      - step:/step:ro
    depends_on:
      step:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
    networks:
      external:
        aliases:
          # Traefik is aliased to all the services that run behind it here.
          # The reason to do this is that step-ca tries to validate the domains
          # by connecting to them, and we'd like it to go through traefik, instead
          # of calling the service containers directly.
          - guessthebook.example.com
          - traefik.local

  step:
    image: smallstep/step-ca:latest
    restart: unless-stopped
    environment:
      - TZ=UTC
      - DOCKER_STEPCA_INIT_NAME=OpenProject Development
      - DOCKER_STEPCA_INIT_DNS_NAMES=step,localhost
      - DOCKER_STEPCA_INIT_PROVISIONER_NAME=openproject
      - DOCKER_STEPCA_INIT_PASSWORD=openproject
      - DOCKER_STEPCA_INIT_ACME=true
    volumes:
      - step:/home/step

volumes:
  step:

networks:
  external:
    name: traefik
    external: true
